// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum VpnStatus: Int, CaseIterable {
  case disconnecting = 0
  case disconnected = 1
  case connecting = 2
  case connected = 3
}

enum RefreshVpnResult: Int, CaseIterable {
  case installed = 0
  case notInstalled = 1
  case waitForApproval = 2
}

enum PlatformPermissionKind: Int, CaseIterable {
  case none = 0
  case androidVpn = 1
  case macosSystemExtension = 2
  case appleVpn = 3
  case androidLocalNetwork = 4
}

enum PlatformPermissionState: Int, CaseIterable {
  case notRequired = 0
  case notDetermined = 1
  case awaitingUserApproval = 2
  case granted = 3
  case denied = 4
  case failed = 5
}

enum NativeVpnCommandState: Int, CaseIterable {
  case success = 0
  case waitingForPlatformPermission = 1
  case failed = 2
}

enum NativeLaunchAtLoginState: Int, CaseIterable {
  case enabled = 0
  case disabled = 1
  case requiresApproval = 2
  case unavailable = 3
  case error = 4
}

/// Generated class from Pigeon that represents data sent in messages.
struct AppleVpnCapabilities: Hashable, CustomStringConvertible {
  var serviceExclusions: Bool
  var deviceCommunication: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AppleVpnCapabilities? {
    let serviceExclusions = pigeonVar_list[0] as! Bool
    let deviceCommunication = pigeonVar_list[1] as! Bool

    return AppleVpnCapabilities(
      serviceExclusions: serviceExclusions,
      deviceCommunication: deviceCommunication
    )
  }
  func toList() -> [Any?] {
    return [
      serviceExclusions,
      deviceCommunication,
    ]
  }
  static func == (lhs: AppleVpnCapabilities, rhs: AppleVpnCapabilities) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.serviceExclusions, rhs.serviceExclusions) && MessagesPigeonInternal.deepEquals(lhs.deviceCommunication, rhs.deviceCommunication)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AppleVpnCapabilities")
    MessagesPigeonInternal.deepHash(value: serviceExclusions, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: deviceCommunication, hasher: &hasher)
  }

  public var description: String {
    return "AppleVpnCapabilities(serviceExclusions: \(String(describing: serviceExclusions)), deviceCommunication: \(String(describing: deviceCommunication)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeLaunchAtLoginResult: Hashable, CustomStringConvertible {
  var state: NativeLaunchAtLoginState
  var message: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeLaunchAtLoginResult? {
    let state = pigeonVar_list[0] as! NativeLaunchAtLoginState
    let message: String? = nilOrValue(pigeonVar_list[1])

    return NativeLaunchAtLoginResult(
      state: state,
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      state,
      message,
    ]
  }
  static func == (lhs: NativeLaunchAtLoginResult, rhs: NativeLaunchAtLoginResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.state, rhs.state) && MessagesPigeonInternal.deepEquals(lhs.message, rhs.message)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeLaunchAtLoginResult")
    MessagesPigeonInternal.deepHash(value: state, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: message, hasher: &hasher)
  }

  public var description: String {
    return "NativeLaunchAtLoginResult(state: \(String(describing: state)), message: \(String(describing: message)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformPermissionResult: Hashable, CustomStringConvertible {
  var kind: PlatformPermissionKind
  var state: PlatformPermissionState
  var message: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformPermissionResult? {
    let kind = pigeonVar_list[0] as! PlatformPermissionKind
    let state = pigeonVar_list[1] as! PlatformPermissionState
    let message: String? = nilOrValue(pigeonVar_list[2])

    return PlatformPermissionResult(
      kind: kind,
      state: state,
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      kind,
      state,
      message,
    ]
  }
  static func == (lhs: PlatformPermissionResult, rhs: PlatformPermissionResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.kind, rhs.kind) && MessagesPigeonInternal.deepEquals(lhs.state, rhs.state) && MessagesPigeonInternal.deepEquals(lhs.message, rhs.message)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformPermissionResult")
    MessagesPigeonInternal.deepHash(value: kind, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: state, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: message, hasher: &hasher)
  }

  public var description: String {
    return "PlatformPermissionResult(kind: \(String(describing: kind)), state: \(String(describing: state)), message: \(String(describing: message)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeVpnCommandResult: Hashable, CustomStringConvertible {
  var state: NativeVpnCommandState
  var status: VpnStatus? = nil
  var permission: PlatformPermissionResult? = nil
  var message: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeVpnCommandResult? {
    let state = pigeonVar_list[0] as! NativeVpnCommandState
    let status: VpnStatus? = nilOrValue(pigeonVar_list[1])
    let permission: PlatformPermissionResult? = nilOrValue(pigeonVar_list[2])
    let message: String? = nilOrValue(pigeonVar_list[3])

    return NativeVpnCommandResult(
      state: state,
      status: status,
      permission: permission,
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      state,
      status,
      permission,
      message,
    ]
  }
  static func == (lhs: NativeVpnCommandResult, rhs: NativeVpnCommandResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.state, rhs.state) && MessagesPigeonInternal.deepEquals(lhs.status, rhs.status) && MessagesPigeonInternal.deepEquals(lhs.permission, rhs.permission) && MessagesPigeonInternal.deepEquals(lhs.message, rhs.message)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeVpnCommandResult")
    MessagesPigeonInternal.deepHash(value: state, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: status, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: permission, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: message, hasher: &hasher)
  }

  public var description: String {
    return "NativeVpnCommandResult(state: \(String(describing: state)), status: \(String(describing: status)), permission: \(String(describing: permission)), message: \(String(describing: message)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AndroidAppInfo: Hashable, CustomStringConvertible {
  var name: String
  var packageName: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AndroidAppInfo? {
    let name = pigeonVar_list[0] as! String
    let packageName = pigeonVar_list[1] as! String

    return AndroidAppInfo(
      name: name,
      packageName: packageName
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      packageName,
    ]
  }
  static func == (lhs: AndroidAppInfo, rhs: AndroidAppInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.name, rhs.name) && MessagesPigeonInternal.deepEquals(lhs.packageName, rhs.packageName)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AndroidAppInfo")
    MessagesPigeonInternal.deepHash(value: name, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: packageName, hasher: &hasher)
  }

  public var description: String {
    return "AndroidAppInfo(name: \(String(describing: name)), packageName: \(String(describing: packageName)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return VpnStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return RefreshVpnResult(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformPermissionKind(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformPermissionState(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NativeVpnCommandState(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NativeLaunchAtLoginState(rawValue: enumResultAsInt)
      }
      return nil
    case 135:
      return AppleVpnCapabilities.fromList(self.readValue() as! [Any?])
    case 136:
      return NativeLaunchAtLoginResult.fromList(self.readValue() as! [Any?])
    case 137:
      return PlatformPermissionResult.fromList(self.readValue() as! [Any?])
    case 138:
      return NativeVpnCommandResult.fromList(self.readValue() as! [Any?])
    case 139:
      return AndroidAppInfo.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? VpnStatus {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? RefreshVpnResult {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformPermissionKind {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformPermissionState {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? NativeVpnCommandState {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? NativeLaunchAtLoginState {
      super.writeByte(134)
      super.writeValue(value.rawValue)
    } else if let value = value as? AppleVpnCapabilities {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? NativeLaunchAtLoginResult {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformPermissionResult {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? NativeVpnCommandResult {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? AndroidAppInfo {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol BridgeHostApi {
  func getTunFilesDir(completion: @escaping (Result<String, Error>) -> Void)
  func readVpnStatus(completion: @escaping (Result<NativeVpnCommandResult, Error>) -> Void)
  func startVpn(completion: @escaping (Result<NativeVpnCommandResult, Error>) -> Void)
  func stopVpn(completion: @escaping (Result<NativeVpnCommandResult, Error>) -> Void)
  func invoke(requestJson: String, completion: @escaping (Result<String, Error>) -> Void)
  func queryPlatformPermission(completion: @escaping (Result<PlatformPermissionResult, Error>) -> Void)
  func requestPlatformPermission(completion: @escaping (Result<PlatformPermissionResult, Error>) -> Void)
  func getInstalledApps(completion: @escaping (Result<[AndroidAppInfo], Error>) -> Void)
  func getAppIcon(packageName: String, completion: @escaping (Result<FlutterStandardTypedData?, Error>) -> Void)
  func useSystemExtension(completion: @escaping (Result<Bool, Error>) -> Void)
  func appleVpnCapabilities(completion: @escaping (Result<AppleVpnCapabilities, Error>) -> Void)
  func queryLaunchAtLogin(completion: @escaping (Result<NativeLaunchAtLoginResult, Error>) -> Void)
  func setLaunchAtLogin(enabled: Bool, completion: @escaping (Result<NativeLaunchAtLoginResult, Error>) -> Void)
  func openLaunchAtLoginSettings(completion: @escaping (Result<Bool, Error>) -> Void)
  func setAppIcon(appIcon: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func getCurrentAppIcon(completion: @escaping (Result<String, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class BridgeHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `BridgeHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: BridgeHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getTunFilesDirChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.onexray.BridgeHostApi.getTunFilesDir\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getTunFilesDirChannel.setMessageHandler { _, reply in
        api.getTunFilesDir { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getTunFilesDirChannel.setMessageHandler(nil)
    }
    let readVpnStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.onexray.BridgeHostApi.readVpnStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readVpnStatusChannel.setMessageHandler { _, reply in
        api.readVpnStatus { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      readVpnStatusChannel.setMessageHandler(nil)
    }
    let startVpnChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.onexray.BridgeHostApi.startVpn\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startVpnChannel.setMessageHandler { _, reply in
        api.startVpn { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startVpnChannel.setMessageHandler(nil)
    }
    let stopVpnChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.onexray.BridgeHostApi.stopVpn\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopVpnChannel.setMessageHandler { _, reply in
        api.stopVpn { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopVpnChannel.setMessageHandler(nil)
    }
    let invokeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.onexray.BridgeHostApi.invoke\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      invokeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestJsonArg = args[0] as! String
        api.invoke(requestJson: requestJsonArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      invokeChannel.setMessageHandler(nil)
    }
    let queryPlatformPermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.onexray.BridgeHostApi.queryPlatformPermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      queryPlatformPermissionChannel.setMessageHandler { _, reply in
        api.queryPlatformPermission { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      queryPlatformPermissionChannel.setMessageHandler(nil)
    }
    let requestPlatformPermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.onexray.BridgeHostApi.requestPlatformPermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestPlatformPermissionChannel.setMessageHandler { _, reply in
        api.requestPlatformPermission { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestPlatformPermissionChannel.setMessageHandler(nil)
    }
    let getInstalledAppsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.onexray.BridgeHostApi.getInstalledApps\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getInstalledAppsChannel.setMessageHandler { _, reply in
        api.getInstalledApps { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getInstalledAppsChannel.setMessageHandler(nil)
    }
    let getAppIconChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.onexray.BridgeHostApi.getAppIcon\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAppIconChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let packageNameArg = args[0] as! String
        api.getAppIcon(packageName: packageNameArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getAppIconChannel.setMessageHandler(nil)
    }
    let useSystemExtensionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.onexray.BridgeHostApi.useSystemExtension\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      useSystemExtensionChannel.setMessageHandler { _, reply in
        api.useSystemExtension { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      useSystemExtensionChannel.setMessageHandler(nil)
    }
    let appleVpnCapabilitiesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.onexray.BridgeHostApi.appleVpnCapabilities\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      appleVpnCapabilitiesChannel.setMessageHandler { _, reply in
        api.appleVpnCapabilities { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      appleVpnCapabilitiesChannel.setMessageHandler(nil)
    }
    let queryLaunchAtLoginChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.onexray.BridgeHostApi.queryLaunchAtLogin\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      queryLaunchAtLoginChannel.setMessageHandler { _, reply in
        api.queryLaunchAtLogin { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      queryLaunchAtLoginChannel.setMessageHandler(nil)
    }
    let setLaunchAtLoginChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.onexray.BridgeHostApi.setLaunchAtLogin\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setLaunchAtLoginChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        api.setLaunchAtLogin(enabled: enabledArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setLaunchAtLoginChannel.setMessageHandler(nil)
    }
    let openLaunchAtLoginSettingsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.onexray.BridgeHostApi.openLaunchAtLoginSettings\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openLaunchAtLoginSettingsChannel.setMessageHandler { _, reply in
        api.openLaunchAtLoginSettings { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      openLaunchAtLoginSettingsChannel.setMessageHandler(nil)
    }
    let setAppIconChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.onexray.BridgeHostApi.setAppIcon\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setAppIconChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let appIconArg = args[0] as! String
        api.setAppIcon(appIcon: appIconArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setAppIconChannel.setMessageHandler(nil)
    }
    let getCurrentAppIconChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.onexray.BridgeHostApi.getCurrentAppIcon\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCurrentAppIconChannel.setMessageHandler { _, reply in
        api.getCurrentAppIcon { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getCurrentAppIconChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol BridgeFlutterApiProtocol {
  func vpnStatusChanged(status statusArg: VpnStatus, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func refreshVpn(result resultArg: RefreshVpnResult, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class BridgeFlutterApi: BridgeFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  func vpnStatusChanged(status statusArg: VpnStatus, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.onexray.BridgeFlutterApi.vpnStatusChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([statusArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func refreshVpn(result resultArg: RefreshVpnResult, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.onexray.BridgeFlutterApi.refreshVpn\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([resultArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
