default_platform(:android)

platform :android do
  lane :deploy do
    upload_to_play_store(
        aab: "../build/app/outputs/bundle/release/app-release.aab",
        release_status: "draft",
        track: "internal",
        timeout: 1200,
    )
    download_universal_apk_from_google_play(
        version_code: ##version_code##,
        destination: "../../output/OneXray-android-universal.apk",
    )
  end
end
